#!/bin/sh
# TODO - maybe install prettier (dev-dep). Solve lint/prettier.
# Then run prettier before linting.


# Run linting
npm run lint

# Check if linting passed
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the issues before committing."
  exit 1
fi
