name: Deploy Front-End

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Step to check out the repository
    - uses: actions/setup-node@v4 # Step to set up Node.js environment
      with:
        node-version: lts/* # Use the latest LTS version of Node.js
    - name: Install dependencies
      run: npm ci # Install project dependencies using npm
    - name: Build project
      run: npm run build # Build the project
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
