name: Check Source Branch for PR to Main
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: ${{ github.event.pull_request.head.ref != 'testing' }}
        run: |
          echo "Error: Only the 'testing' branch can create PRs to 'main'."
          exit 1